{
 "title": "Weather",
 "description": "Weather dashboard with units in °F",
 "time": { "from": "2025-09-07T04:00:00.000Z", "to": "2025-09-18T03:59:59.000Z" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_LOKI", "query": "loki" },
   { "name": "location", "label": "Location", "query": "label_values(location)" }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "description": "he single-point air temperature the dashboard predicts for the selected day and time (°F)",
   "gridPos": { "h": 11, "w": 14, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(weather_temp_c{job=\"weather-service\", location=~\"$location\"}) by (location) * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "timeseries",
   "description": "the forecast strength of ultraviolet radiation at ground level and how much sun protection you should use.",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(weather_uv_index{job=\"weather-service\",location=~\"$location\"}) by (location)",
     "legendFormat": "Actual UV Index - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_uv_index{job=\"weather-service\", location=~\"$location\"}) by (location)",
     "legendFormat": "Predicted UV Index - {{ location }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "the percentage of water vapor in the air that indicates how dry or muggy it will feel.",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg(weather_humidity{job=\"weather-service\", location=~\"$location\"}) by (location)",
     "legendFormat": "Actual Humidity - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_humidity{job=\"weather-service\", location=~\"$location\", forecast_day=\"0\"}) by (location)",
     "legendFormat": "Predicted Humidity - {{ location }}"
    }
   ]
  },
  {
   "title": "RAINFALL",
   "type": "timeseries",
   "description": "the total expected rainfall (in inches) for the displayed period, showing whether to expect dry conditions or wet weather.",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(weather_precip_mm{job=\"weather-service\",location=~\"$location\"}) by (location)",
     "legendFormat": "Actual Precipitation - {{ location }}"
    },
    {
     "expr": "avg(weather_forecast_precip_mm{job=\"weather-service\", location=~\"$location\", forecast_day=\"0\"}) by (location)",
     "legendFormat": "Predicted Precipitation - {{ location }}"
    }
   ]
  },
  {
   "title": "Condition",
   "type": "state-timeline",
   "description": "the short weather label describing overall sky and precipitation conditions for the period.",
   "gridPos": { "h": 8, "w": 14, "x": 2, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"weather-service\"} |= \"Current Condition\" | logfmt | location=~\"$location\""
    }
   ]
  },
  {
   "title": "WIND",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "expr": "avg(weather_wind_speed{job=\"weather-service\",location=~\"$location\"}) by (location) * 0.6213711922",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(weather_forecast_uv_index{job=\"weather-service\", location=~\"$location\", forecast_day=~\"$forecast_day\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "barchart",
   "description": "the single-point air temperature the dashboard predicts for the selected day and time (°F).",
   "gridPos": { "h": 5, "w": 20, "x": 2, "y": 19 },
   "repeat": "DS_PROMETHEUS",
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "parser": "simple",
     "source": "url",
     "type": "json",
     "url": "https://jolly-butterfly-2e8a.shadabchow.workers.dev/?lat=40.710335&lon=-73.99309&days=10&unit=fahrenheit",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "10-DAY FORECAST",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 7, "x": 2, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "parser": "simple",
     "source": "url",
     "type": "json",
     "url": "https://jolly-butterfly-2e8a.shadabchow.workers.dev/?lat=40.710335&lon=-73.99309&days=10&unit=fahrenheit",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Feels Like",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(weather_feelslike_temp_c{job=\"weather-service\", location=~\"$location\"}) by (location) * 1.8 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(weather_wind_speed{job=\"weather-service\",location=~\"$location\"}) by (location) * 0.6213711922",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 13, "w": 6, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "avg(weather_location_info{job=\"weather-service\", location=~\"$location\"}) by (location,lat,lon)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAINFALL",
   "type": "stat",
   "description": "the total expected rainfall (in inches) for the displayed period, showing whether to expect dry conditions or wet weather.",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(weather_precip_mm{job=\"weather-service\",location=~\"$location\"}) by (location)* 0.03937007874",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(weather_humidity{job=\"weather-service\", location=~\"$location\"}) by (location)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 10, "x": 6, "y": 37 }, "options": { "content": "---" } }
 ]
}